### ISSUE TITLE
GET REQUEST EMPTY

### ISSUE THREAD

**Issue by darke-f** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-hahahihi#1]
Request get yang dikirimkan ke hosting selalu mengembalikan isi_data yang kosong walaupun sudah dilakukan pengisian data melalui Request POST yang ada.

**Comment by naufalpf** [comment]
Halo @darke-f
Kemarin memang ada perbedaan struktur pada `Database` dan API kami. Silahkan di cek kembali
