### ISSUE TITLE
database kurang sesuai

### ISSUE THREAD

**Issue by faizalmuzakki** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-hahahihi#2]
1. Mahasiswa harusnya bisa punya banyak matkul.
2. Kalau input nrp yang sama harusnya tidak bisa.
3. Absensi harusnya pakai ruang, kalau cuma pakai nrp dan pertemuan nggak bisa tau dia absen di mata kuliah apa.

**Comment by Akram001** [comment]
issues no 1 2 3 udah beres

**Comment by naufalpf** [comment]
Halo @faizalmuzakki, 
Kami sudah memperbaiki database kami sesuai API dan ketiga masalah diatas sudah kami coba selesaikan. 
Kami melakukan update di `commit `terbaru kami [8f7b71b](https://github.com/2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-hahahihi/commit/8a85010bc9502076d6cf967d2d7123f0a3f05837). Mohon dicoba kembali

**Comment by naufalpf** [comment]
Halo @faizalmuzakki, 
Kami sudah memperbaiki database kami sesuai API dan ketiga masalah diatas sudah terselesaikan. 
Kami melakukan update di `commit `terbaru kami [d3aef6e](https://github.com/2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-hahahihi/commit/e035ae8cc6d0f836333cdbfa02730492bca504c2). Dimohon untuk membaca dokumentasi **Readme** untuk mengujicoba APInya. Untuk akses Link [API](http://9884449c.ngrok.io) atau local TC http://10.151.33.43:8000
